### ISSUE TITLE
Pilot tones too long

### ISSUE THREAD

**Issue by discoHR** [raydac/zxtap-to-wav#1]
Hi,

The pilot tone on both header and headerless blocks is about 2-3 times longer than original Spectrum pilot. Is there a reason for that?

It doesn't affect functionality but wastes a hefty amount of tape space when you save 9 games per tape side, each containing about 6 pilots, that's 54 pilots times 2-3 seconds, 108-162 seconds is wasted per tape side just on extra long pilots.

Could it be that TAP files themselves contain such long pilots? If so, please ignore this issue.

**Comment by raydac** [comment]
I generate 8063 impulses in pilot tone as standard requires, as a variant I can add parameter to generate custom number of pilot tone impulses

**Comment by discoHR** [comment]
You're actually outputting twice the amount of the pilot pulses.

TapeBlock.go:69
for i := 0; i < pilotImpulses / 2; i++ {

That should fix it.

**Comment by raydac** [comment]
I didn't catch, standard requires 8063 impulses for header pilot tone and 3223 impulses for data block pilot tone, in the loop I write such number of impulses, with your code I just will decrease their number, what about compatibility?

**Comment by raydac** [comment]
ok, looks like I am wrong and exactly [making to long headers](https://faqwiki.zxnet.co.uk/wiki/Spectrum_tape_interface)

**Comment by discoHR** [comment]
Read this...
https://faqwiki.zxnet.co.uk/wiki/Spectrum_tape_interface

Quote:
> A 'pulse' here is either a mark or a space, so **2 pulses makes a complete square wave cycle**.
> Pilot tone: before each block is a sequence of 8063 (header) or 3223 (data) pulses, each of length 2168 T-states.

Regarding the compatibility, try saving something on the real Spectrum and measure the pilot length on both header and code blocks. You will never get pilots as long as they are now in zxtap2wav. ROM loading routine require at least a second of pilot tone, you have over 10 seconds while there should be 5.

**Comment by raydac** [comment]
I have fixed the issue in [1.0.1-SNAPSHOT](https://github.com/raydac/zxtap-to-wav/releases/tag/1.0.1)

**Comment by discoHR** [comment]
I've tried it, it's perfect now. Thanks.
