### ISSUE TITLE
File infected with a virus!!

### ISSUE THREAD

**Issue by kattan1969** [raydac/zxtap-to-wav#2]
Hi,
An amazing tool for the ZX Spectrum. However, one of the files is infected with a virus!
Check zxtap2wav-windows-386.exe, it's infected with Gen:Variant.Zusy.256843 as reported by my BitDefender.

**Comment by raydac** [comment]
hi
thank you for the info, it is false positive detection, I have rebuilt with latest GoSDK 1.14 and removed stripping of files, it should decrease probability for false positive cases
