### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by lackovic** [raydac/zxtap-to-wav#4]
Using [the release 1.0.1](https://github.com/raydac/zxtap-to-wav/releases/download/1.0.1/zxtap2wav-windows-amd64.exe) with [this tap file](https://www.planetemu.net/rom/sinclair-zx-spectrum-tap/underground-19xx-skorpyo-sp), when running:
```
.\zxtap2wav-windows-amd64.exe -i '.\Underground (19xx)(Skorpyo)(Sp).tap'
``` 
I get:
```
  TAP2WAV converter of .TAP files (a format for ZX-Spectrum emulators) into its .WAV image (PCM, mono).
  Project page : https://github.com/raydac/zxtap-to-wav
        Author : Igor Maznitsa (http://www.igormaznitsa.com)
       Version : 1.0.1

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/raydac/zxtap-zxtape.ReadTapeBlock({0x89d688, 0xc00004e028})
        /home/igorm/Projects/Pet/zxtap-to-wav/src/zxtape/TapeBlock.go:124 +0x65
main.ParseTap({0x89d688, 0xc00004e028})
        /home/igorm/Projects/Pet/zxtap-to-wav/src/main.go:56 +0x56
main.loadTapFile({0xc00000e3c0?, 0xc00000e3c0?})
        /home/igorm/Projects/Pet/zxtap-to-wav/src/main.go:79 +0xb8
main.main()
        /home/igorm/Projects/Pet/zxtap-to-wav/src/main.go:177 +0x185
``` 
Any idea what I could do to fix this issue?

**Comment by raydac** [comment]
there was bug with read of zero length blocks, you can try [1.0.2](https://github.com/raydac/zxtap-to-wav/releases/tag/1.0.2)

**Comment by lackovic** [comment]
> there was bug with read of zero length blocks, you can try [1.0.2](https://github.com/raydac/zxtap-to-wav/releases/tag/1.0.2)

I am not able to download the `exe` file anymore as Windows recognizes it as potentially dangerous.

I tried with Chrome, Edge and from PowerShell with `wget`.

Can you suggest another way to download it?

**Comment by lackovic** [comment]
It worked, thanks! This was the output:
```
  TAP2WAV converter of .TAP files (a format for ZX-Spectrum emulators) into its .WAV image (PCM, mono).
  Project page : https://github.com/raydac/zxtap-to-wav
        Author : Igor Maznitsa (http://www.igormaznitsa.com)
       Version : 1.0.2

Detected data blocks : P.D.$.D.C.D.C.D
The Result WAV file size is 6397 Kb
```
